// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataNormalizer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240603025229_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataNormalizer.Models.CityModel", b =>
                {
                    b.Property<int>("cityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cityID"));

                    b.Property<string>("cityName")
                        .HasColumnType("longtext");

                    b.HasKey("cityID");

                    b.ToTable("ciudades_norm");
                });

            modelBuilder.Entity("DataNormalizer.Models.FamousModel", b =>
                {
                    b.Property<int>("famousID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("famousID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("famousName")
                        .HasColumnType("longtext");

                    b.Property<string>("formattedBirthDate")
                        .HasColumnType("longtext");

                    b.Property<bool>("isBirthday")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("famousID");

                    b.ToTable("fnac_famosos_norm");
                });

            modelBuilder.Entity("DataNormalizer.Models.UnformattedModel", b =>
                {
                    b.Property<int>("unformFamousID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("unformFamousID"));

                    b.Property<string>("unformBirthDate")
                        .HasColumnType("longtext");

                    b.Property<string>("unformName")
                        .HasColumnType("longtext");

                    b.HasKey("unformFamousID");

                    b.ToTable("fnac_famosos");
                });

            modelBuilder.Entity("NormalizedAddresses", b =>
                {
                    b.Property<int>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("address_id"));

                    b.Property<string>("city_state_prov")
                        .HasColumnType("longtext");

                    b.Property<string>("street_name")
                        .HasColumnType("longtext");

                    b.Property<string>("street_number")
                        .HasColumnType("longtext");

                    b.HasKey("address_id");

                    b.ToTable("direcciones");
                });

            modelBuilder.Entity("NormalizedGeoreference", b =>
                {
                    b.Property<int>("georeference_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("georeference_id"));

                    b.Property<string>("latitud")
                        .HasColumnType("longtext");

                    b.Property<string>("longitud")
                        .HasColumnType("longtext");

                    b.HasKey("georeference_id");

                    b.ToTable("georeferencias");
                });

            modelBuilder.Entity("NormalizedPlace", b =>
                {
                    b.Property<int>("place_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("place_id"));

                    b.Property<string>("place_name")
                        .HasColumnType("longtext");

                    b.HasKey("place_id");

                    b.ToTable("lugares");
                });
#pragma warning restore 612, 618
        }
    }
}
